### PR TITLE
Fix create service frontend

### LINKED ISSUE #8: Create service not functioning
Most likely because were not doing anything with Authorization in the header (refer to the api docs https://documenter.getpostman.com/view/5785834/RzZ6HLLg#fb705fcb-fc10-490b-b701-259f281ee1d6)

### PR DESCRIPTION
**Pull request by steevejoseph**
Went through the frontend, fixed some naming, datatype, and state bugs. Also added the authorization header and got 201's from the API 🎉 

However, the UI still doesn't respond indicating something happened.
Hopefully fixes #8

### CODE REVIEW

File: src/actions/index.js [hunk 1]
```diff
@@ -75,10 +83,15 @@ export function serviceView(id) {
     };
 }
 
-export function getUserFromLocalStorage() { 
+export function getUserFromLocalStorage() {
+    
+        // console.log(typeof(localStorage.getItem('loggedInUser')));
+        const user = JSON.parse(localStorage.getItem('loggedInUser'));
+        // console.log(typeof(user));
```
Comment (abeSanchez) [inline src/actions/index.js]: please remove logs. Thanks :)

Comment (abeSanchez) [reply src/actions/index.js]: and empty lines

File: src/components/create_service.js [hunk 2]
```diff
@@ -29,12 +29,15 @@ class CreateService extends Component {
     }
 
     onSubmit(values) {
+        // add the user so "owner" can be properly assigned.
```
Comment (abeSanchez) [inline src/components/create_service.js]: Please capitalize comments

File: src/components/create_service.js [hunk 3]
```diff
@@ -29,12 +29,15 @@ class CreateService extends Component {
...
+        values = { ...values, user:this.props.user}
         this.props.createService(values, () => {
             this.props.history.push("/");
         });
     }
 
     render() {
+        // console.log(this.props.token)
```
Comment (abeSanchez) [inline src/components/create_service.js]: logs logs logs

File: src/components/create_service.js [hunk 4]
```diff
@@ -78,9 +81,23 @@ function validate(values) {
     return errors;
 }
 
+// let the form know that there's a user in the house.
+function mapStateToProps(state) {
+
+    const user = JSON.parse(state.user.user);
+    
+    // yep, gotta parse this one too. (Errant double quotes if otherwise)
```
Comment (abeSanchez) [inline src/components/create_service.js]: remove these comments lol

File: src/reducers/user_reducer.js [hunk 5]
```diff
@@ -7,21 +7,31 @@ export default function(state = {}, action) {
             return state;
         case LOGIN: 
             if (action.payload.status === 200) {
+                // console.log(typeof(action.payload.data.token));                
+                // console.log(action.payload.data);
```
Comment (abeSanchez) [inline src/reducers/user_reducer.js]: natural log

File: src/reducers/user_reducer.js [hunk 6]
```diff
@@ -7,21 +7,31 @@ export default function(state = {}, action) {
...
             }
             return state;
         case GET_USER_FROM_LOCAL_STORAGE:
             return {
+                ...state,
                 loggedIn: true,
-                user: localStorage.getItem('loggedInUser')
+                user: localStorage.getItem('loggedInUser'),
+                token: localStorage.getItem('token')
+
```
Comment (abeSanchez) [inline src/reducers/user_reducer.js]: remove empty line

File: src/reducers/user_reducer.js [hunk 7]
```diff
@@ -7,21 +7,31 @@ export default function(state = {}, action) {
...
             }
         case LOG_OUT_USER:
             return {
-                loggedIn: false
+                ...state,
+                loggedIn: false,
+
```
Comment (abeSanchez) [inline src/reducers/user_reducer.js]: empty line

File: src/actions/index.js [hunk 8]
```diff
@@ -11,6 +11,13 @@ export const FETCH_USER = 'fetch_user';
 export const GET_USER_FROM_LOCAL_STORAGE = 'get_local_from_storage';
 export const LOG_OUT_USER = 'log_out';
 
+// set authorization header.    
+// gotta JSON.parse here as well.. (Errant double quotes).
+axios.defaults.headers.common['Authorization'] = 'Bearer ' + JSON.parse(localStorage.getItem("token"));
+
+//sanity check
+// console.log(axios.defaults.headers.common['Authorization']);
```
Comment (abeSanchez) [inline src/actions/index.js]: cut this log and remove unnecessary comments
